.\" # Copyright 2010-2022 David Robillard <d@drobilla.net>
.\" # SPDX-License-Identifier: CC-BY-SA-4.0 or GPL-3.0-or-later
.Dd November 30, 2022
.Dt PATCHAGE 1
.Os Patchage 1.0.11
.Sh NAME
.Nm patchage
.Nd graphically connect JACK/ALSA audio/MIDI applications
.Sh SYNOPSIS
.Nm patchage
.Op Fl AJVh
.Op Fl Fl help
.Op Fl Fl no-alsa
.Op Fl Fl no-jack
.Op Fl Fl version
.Sh DESCRIPTION
.Nm
provides a graphical interface to connect JACK and ALSA inputs and outputs.
Each application is represented on a canvas as a
.Dq module ,
with inputs on the left and outputs on the right.
Modules can be arranged manually or automatically to have a clear display of the current setup.
.Pp
The options are as follows:
.Pp
.Bl -tag -compact -width 3n
.It Fl A , Fl Fl no-alsa
Do not automatically attach to ALSA.
.Pp
.It Fl J , Fl Fl no-jack
Do not automatically attach to JACK.
.Pp
.It Fl V , Fl Fl version
Display version information and exit.
.Pp
.It Fl h , Fl Fl help
Print the command line options.
.El
.Sh EXIT STATUS
.Nm
exits with a status of 0, or non-zero if an error occurred.
.Sh AUTHORS
.Nm
was written by
.An David Robillard
.Aq Mt d@drobilla.net .
